name: Composite Action
description: 'Testing the composite action'
inputs:
      environment:
        description: 'Environment to run the jobs'
        required: true

runs:
  using: 'composite'
  steps:
    - name: Get the code
      uses: actions/checkout@v4
      with:
        environment::{{ github.events.inputs.environment }}
    - name: 'Set up node'
      uses: actions/setup-node@v4
      with:|
        node-version: '22'
        environment:{{ github.events.inputs.environment }}
    - name: 'Install dependencies'
      run: npm ci:{{ github.events.inputs.environment }}
      shell: bash

    
