name: Composite Action 
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up node'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: 'Install dependencies'
        run: npm ci
        
        
