name: Composite Action
description: 'Testing the composite action'
runs:
  using: 'composite'
  steps:
    - name: 'Set up node'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: 'Install dependencies'
      run: npm ci
