name: Composite Action
description: 'Testing the composite action'
inputs:
      environment:
        description: 'Environment to run the jobs'
        required: true
        type: choice
        options:
          - production
          - staging
          - qa
          - dev
        default: production

runs:
  using: 'composite'
  steps:
    - name: Get the code
      uses: actions/checkout@v4
    - name: 'Set up node'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: 'Install dependencies'
      run: npm ci
      shell: bash

    
