name: Deploy website
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environments based on options'
        type: choice
        options:
          - production
          - staging
          - qa
          - dev
      
      notify:
        description: 'Deployment notification'
        required: true
        type: boolean
        default: false
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code and set up node
        uses: ./.github/actions
        with:
          environment: ${{ github.events.inputs.environment }}
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code and set up node
        uses: ./.github/actions
        with:
          environment: ${{ github.events.inputs.environment }}
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output files
        run: ls
      - name: Deploy
        run: echo "Deploying..."
