name: Path specific file push
on:
  push: 
    paths:
      - 'src/components/MainContent.test.jsx'

jobs:
  lint:
    runs-on: ububtu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Code Linting
        run: npm run lint
        
