name: Reusablle workflow
on: 
      workflow_call:
            inputs:
                  code_checkout:
                    required: true
                    type: string
                    description: 'Checkout the code'
                  setup_node:
                    required: true
                    type: string
                    default: '18'
                    description: 'Installing node'
                  dependency_install:
                    required: true
                    type: string
                    description: 'Installing dependencies'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/checkout@v4
        with:
          node-version: ${{ inputs.setup_node.default }}
      - name: Build dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
