name: Reusablle workflow
on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '18'
        description: 'Node.js version to use'
      stage:
        required: false
        type: string
        description: 'Pipeline stage to run (lint/test/build/deploy)'
      environment:
        required: false
        type: string
        description: 'Environment to deploy on'

jobs:
  pipeline-stage:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        if: inputs.stage == 'lint'
        run: |
          npm run lint

      - name: Run tests
        if: inputs.stage == 'test'
        run: |
          npm run test

      - name: Build
        if: inputs.stage == 'build'
        run: |
          npm run build

      - name: Deploy
        if: inputs.stage == 'deploy'
        run: |
          npm run deploy
