name: Using reusable workflow
on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint checking
    uses: ./.github/workflows/reusable_workflow.yaml
  test:
    name: Run test
    needs: lint
    uses: ./.github/workflows/reusable_workflow.yaml
  build:
    name: Builds Application
    uses: ./.github/workflows/reusable_workflow.yaml
