name: Using reusable workflow
on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: ./.github/workflows/reusable_workflow.yaml
      - name: Set up node
        uses: ./.github/workflows/reusable_workflow.yaml
        with:
          node-version: '18'
      - name: Install dependencies
        run: ./.github/workflows/reusable_workflow.yaml
      - name: Run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: ./.github/workflows/reusable_workflow.yaml
      - name: Set up node
        uses: ./.github/workflows/reusable_workflow.yaml
        with:
          node-version: '18'
      - name: Install dependencies
        run: ./.github/workflows/reusable_workflow.yaml
      - name: Run the tests
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
       - name: Code checkout
         uses: ./.github/workflows/reusable_workflow.yaml
       - name: Set up node
         uses: ./.github/workflows/reusable_workflow.yaml
         with:
           node-version: '18'
       - name: Install dependencies
         run: ./.github/workflows/reusable_workflow.yaml
       - name: Build the code
         run: npm run build
  deploy:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: Running the deploy
        run: echo "Deployment initiated..."
      
      
